clean repo without secrets

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -1,10 +1,89 @@
+# name: ETL CI Pipeline
+
+# on:
+#   push:
+#     branches: [ "main" ]
+#   pull_request:
+#     branches: [ "main" ]
+
+# jobs:
+#   build-test:
+#     runs-on: ubuntu-latest
+
+#     services:
+#       postgres:
+#         image: postgres:15
+#         env:
+#           POSTGRES_USER: postgres
+#           POSTGRES_PASSWORD: postgres
+#           POSTGRES_DB: order_quality_analytics_db
+#         ports:
+#           - 5432:5432
+#         options: >-
+#           --health-cmd="pg_isready -U postgres"
+#           --health-interval=10s
+#           --health-timeout=5s
+#           --health-retries=5
+
+#     steps:
+#       - name: Checkout code
+#         uses: actions/checkout@v4
+
+#       - name: Set up Python
+#         uses: actions/setup-python@v5
+#         with:
+#           python-version: "3.10"
+
+#       - name: Install dependencies
+#         run: |
+#           python -m pip install --upgrade pip
+#           pip install -r requirements.txt
+
+#       - name: Install dbt
+#         run: |
+#           pip install dbt-postgres
+
+#       - name: Create dbt profiles.yml
+#         run: |
+#           mkdir -p ~/.dbt
+#           cat <<EOF > ~/.dbt/profiles.yml
+#           order_analytics:
+#             target: dev
+#             outputs:
+#               dev:
+#                 type: postgres
+#                 host: localhost
+#                 user: postgres
+#                 password: postgres
+#                 port: 5432
+#                 dbname: order_quality_analytics_db
+#                 schema: public
+#                 threads: 1
+#           EOF
+
+#       - name: Run tests
+#         run: |
+#           pytest -v
+
+#       - name: Run dbt
+#         working-directory: order_analytics
+#         run: |
+#           dbt debug
+#           dbt deps || true
+#           dbt run
+
+
+
 name: ETL CI Pipeline
 
 on:
   push:
-    branches: [ "main" ]
+    branches: ["main"]
   pull_request:
-    branches: [ "main" ]
+    branches: ["main"]
+
+env:
+  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
 
 jobs:
   build-test:
@@ -38,9 +117,6 @@ jobs:
         run: |
           python -m pip install --upgrade pip
           pip install -r requirements.txt
-
-      - name: Install dbt
-        run: |
           pip install dbt-postgres
 
       - name: Create dbt profiles.yml
@@ -62,8 +138,7 @@ jobs:
           EOF
 
       - name: Run tests
-        run: |
-          pytest -v
+        run: pytest -v
 
       - name: Run dbt
         working-directory: order_analytics
